[2016-07-06 18:57:51,336] [ERROR] [__main__-1832.log] [device_center_client.py:_connect:405]  [connect failed]
